# Site settings
title: A blog about Sally Kim
description: A blog about Sally Kim
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SallyKimOh.github.io" # the base hostname & protocol for your site

# User settings
username: Sally Developer
user_description: Highly competent in large-scale system development, database design, portal website development, intranet system development and network programming.
user_title: Software Developer
email: sallykimoh@gmail.com
twitter_username: lorem_ipsum
github_username:  SallyKimOh
gplus_username:  sally-kim-oh/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
